server:
  tomcat:
    max-threads: 800
    min-spare-threads: 20
    accesslog:
      enabled: true
      directory: /usr/local/springboot-api/
      pattern: "%h %l %u %t &quot;%r&quot; %s %b"
      prefix: "localhost_access_log"
      suffix: ".txt"
  port: 8080
spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    time-zone: GMT+8
  datasource:
    druid:
      pool-prepared-statements: true
      filters: stat,wall,log4j
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 3000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #reset-enable:
        login-username: admin
        login-password: 7815696ecbf1c96e6894b779456d330e
        #allow: 47.92.143.86
        #deny:
      aop-patterns: com.yuqi.demo.service.*
      web-stat-filter:
        enabled: true
    type: com.alibaba.druid.pool.DruidDataSource
    #数据库
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

logging:
  #file: springboot.log
  level:
    org:
      mybatis: INFO
      springframework: INFO
    com.yuqi.demo.dao: debug
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#mybatis
mybatis:
  type-aliases-package: com.yuqi.demo.entity
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    call-setters-on-nulls: true
#tkmapper
#mapper:
#  mappers:
#    - com.yuqi.demo.dao
#  not-empty: false
#  identity: mysql
#  style: camelhumpAndLowercase
#  safeDelete: true
#  safeUpdate: true