package com.yuqi.demo.dao;

import com.yuqi.demo.entity.CmsStaticArticle;
import com.yuqi.demo.entity.CmsStaticArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmsStaticArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_static_article
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    long countByExample(CmsStaticArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_static_article
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    int deleteByExample(CmsStaticArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_static_article
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    int deleteByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_static_article
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    int insert(CmsStaticArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_static_article
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    int insertSelective(CmsStaticArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_static_article
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    List<CmsStaticArticle> selectByExampleWithBLOBs(CmsStaticArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_static_article
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    List<CmsStaticArticle> selectByExample(CmsStaticArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_static_article
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    CmsStaticArticle selectByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_static_article
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    int updateByExampleSelective(@Param("record") CmsStaticArticle record, @Param("example") CmsStaticArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_static_article
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    int updateByExampleWithBLOBs(@Param("record") CmsStaticArticle record, @Param("example") CmsStaticArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_static_article
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    int updateByExample(@Param("record") CmsStaticArticle record, @Param("example") CmsStaticArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_static_article
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    int updateByPrimaryKeySelective(CmsStaticArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_static_article
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    int updateByPrimaryKeyWithBLOBs(CmsStaticArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_static_article
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    int updateByPrimaryKey(CmsStaticArticle record);
}