package com.yuqi.demo.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_static_article
 */
public class CmsStaticArticle {
    /**
     * Database Column Remarks:
     *   静态页ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.article_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private Integer articleId;

    /**
     * Database Column Remarks:
     *   分类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.class_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private Integer classId;

    /**
     * Database Column Remarks:
     *   分类类型:1-资讯;2-帮助模板;3-专题页;4-公告
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.class_type
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private Boolean classType;

    /**
     * Database Column Remarks:
     *   平台ID:1=好药师官网
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.platform_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private Integer platformId;

    /**
     * Database Column Remarks:
     *   点击数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.article_clicks
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private Integer articleClicks;

    /**
     * Database Column Remarks:
     *   文章标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.article_name
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String articleName;

    /**
     * Database Column Remarks:
     *   作者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.article_writer
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String articleWriter;

    /**
     * Database Column Remarks:
     *   来源
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.article_source
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String articleSource;

    /**
     * Database Column Remarks:
     *   缩略图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.thumbnail
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String thumbnail;

    /**
     * Database Column Remarks:
     *   SEO标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.seo_title
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String seoTitle;

    /**
     * Database Column Remarks:
     *   SEO关键词
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.seo_keywords
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String seoKeywords;

    /**
     * Database Column Remarks:
     *   SEO描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.seo_desc
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String seoDesc;

    /**
     * Database Column Remarks:
     *   病症id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.illness_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String illnessId;

    /**
     * Database Column Remarks:
     *   病症名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.illness_name
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String illnessName;

    /**
     * Database Column Remarks:
     *   文件名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.file_name
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String fileName;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.article_sort
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private Byte articleSort;

    /**
     * Database Column Remarks:
     *   是否审核:0=未审核;1=已审核;2=审核未通过
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.audit_status
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private Boolean auditStatus;

    /**
     * Database Column Remarks:
     *   审核时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.audit_time
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private Date auditTime;

    /**
     * Database Column Remarks:
     *   审核人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.audit_user_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String auditUserId;

    /**
     * Database Column Remarks:
     *   审核不通过原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.audit_not_pass_reason
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String auditNotPassReason;

    /**
     * Database Column Remarks:
     *   是否生成:0-未生成;1-已生成
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.is_generate
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private Boolean isGenerate;

    /**
     * Database Column Remarks:
     *   生成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.generate_time
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private Date generateTime;

    /**
     * Database Column Remarks:
     *   生成人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.generate_user_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String generateUserId;

    /**
     * Database Column Remarks:
     *   数据爬取时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.spider_time
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private Date spiderTime;

    /**
     * Database Column Remarks:
     *   是否可用:0=否;1=是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.is_enabled
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private Boolean isEnabled;

    /**
     * Database Column Remarks:
     *   是否删除:0=否;1=是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.is_delete
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private Boolean isDelete;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.create_time
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.create_user
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String createUser;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.update_time
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.update_user
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String updateUser;

    /**
     * Database Column Remarks:
     *   文章内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_static_article.article_content
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    private String articleContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.article_id
     *
     * @return the value of cms_static_article.article_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.article_id
     *
     * @param articleId the value for cms_static_article.article_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.class_id
     *
     * @return the value of cms_static_article.class_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.class_id
     *
     * @param classId the value for cms_static_article.class_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.class_type
     *
     * @return the value of cms_static_article.class_type
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public Boolean getClassType() {
        return classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.class_type
     *
     * @param classType the value for cms_static_article.class_type
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setClassType(Boolean classType) {
        this.classType = classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.platform_id
     *
     * @return the value of cms_static_article.platform_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public Integer getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.platform_id
     *
     * @param platformId the value for cms_static_article.platform_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.article_clicks
     *
     * @return the value of cms_static_article.article_clicks
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public Integer getArticleClicks() {
        return articleClicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.article_clicks
     *
     * @param articleClicks the value for cms_static_article.article_clicks
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setArticleClicks(Integer articleClicks) {
        this.articleClicks = articleClicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.article_name
     *
     * @return the value of cms_static_article.article_name
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getArticleName() {
        return articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.article_name
     *
     * @param articleName the value for cms_static_article.article_name
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setArticleName(String articleName) {
        this.articleName = articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.article_writer
     *
     * @return the value of cms_static_article.article_writer
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getArticleWriter() {
        return articleWriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.article_writer
     *
     * @param articleWriter the value for cms_static_article.article_writer
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setArticleWriter(String articleWriter) {
        this.articleWriter = articleWriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.article_source
     *
     * @return the value of cms_static_article.article_source
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getArticleSource() {
        return articleSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.article_source
     *
     * @param articleSource the value for cms_static_article.article_source
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setArticleSource(String articleSource) {
        this.articleSource = articleSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.thumbnail
     *
     * @return the value of cms_static_article.thumbnail
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.thumbnail
     *
     * @param thumbnail the value for cms_static_article.thumbnail
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.seo_title
     *
     * @return the value of cms_static_article.seo_title
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getSeoTitle() {
        return seoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.seo_title
     *
     * @param seoTitle the value for cms_static_article.seo_title
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setSeoTitle(String seoTitle) {
        this.seoTitle = seoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.seo_keywords
     *
     * @return the value of cms_static_article.seo_keywords
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getSeoKeywords() {
        return seoKeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.seo_keywords
     *
     * @param seoKeywords the value for cms_static_article.seo_keywords
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setSeoKeywords(String seoKeywords) {
        this.seoKeywords = seoKeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.seo_desc
     *
     * @return the value of cms_static_article.seo_desc
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getSeoDesc() {
        return seoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.seo_desc
     *
     * @param seoDesc the value for cms_static_article.seo_desc
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setSeoDesc(String seoDesc) {
        this.seoDesc = seoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.illness_id
     *
     * @return the value of cms_static_article.illness_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getIllnessId() {
        return illnessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.illness_id
     *
     * @param illnessId the value for cms_static_article.illness_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setIllnessId(String illnessId) {
        this.illnessId = illnessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.illness_name
     *
     * @return the value of cms_static_article.illness_name
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getIllnessName() {
        return illnessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.illness_name
     *
     * @param illnessName the value for cms_static_article.illness_name
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setIllnessName(String illnessName) {
        this.illnessName = illnessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.file_name
     *
     * @return the value of cms_static_article.file_name
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.file_name
     *
     * @param fileName the value for cms_static_article.file_name
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.article_sort
     *
     * @return the value of cms_static_article.article_sort
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public Byte getArticleSort() {
        return articleSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.article_sort
     *
     * @param articleSort the value for cms_static_article.article_sort
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setArticleSort(Byte articleSort) {
        this.articleSort = articleSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.audit_status
     *
     * @return the value of cms_static_article.audit_status
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public Boolean getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.audit_status
     *
     * @param auditStatus the value for cms_static_article.audit_status
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setAuditStatus(Boolean auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.audit_time
     *
     * @return the value of cms_static_article.audit_time
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.audit_time
     *
     * @param auditTime the value for cms_static_article.audit_time
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.audit_user_id
     *
     * @return the value of cms_static_article.audit_user_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getAuditUserId() {
        return auditUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.audit_user_id
     *
     * @param auditUserId the value for cms_static_article.audit_user_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setAuditUserId(String auditUserId) {
        this.auditUserId = auditUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.audit_not_pass_reason
     *
     * @return the value of cms_static_article.audit_not_pass_reason
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getAuditNotPassReason() {
        return auditNotPassReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.audit_not_pass_reason
     *
     * @param auditNotPassReason the value for cms_static_article.audit_not_pass_reason
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setAuditNotPassReason(String auditNotPassReason) {
        this.auditNotPassReason = auditNotPassReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.is_generate
     *
     * @return the value of cms_static_article.is_generate
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public Boolean getIsGenerate() {
        return isGenerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.is_generate
     *
     * @param isGenerate the value for cms_static_article.is_generate
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setIsGenerate(Boolean isGenerate) {
        this.isGenerate = isGenerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.generate_time
     *
     * @return the value of cms_static_article.generate_time
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public Date getGenerateTime() {
        return generateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.generate_time
     *
     * @param generateTime the value for cms_static_article.generate_time
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setGenerateTime(Date generateTime) {
        this.generateTime = generateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.generate_user_id
     *
     * @return the value of cms_static_article.generate_user_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getGenerateUserId() {
        return generateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.generate_user_id
     *
     * @param generateUserId the value for cms_static_article.generate_user_id
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setGenerateUserId(String generateUserId) {
        this.generateUserId = generateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.spider_time
     *
     * @return the value of cms_static_article.spider_time
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public Date getSpiderTime() {
        return spiderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.spider_time
     *
     * @param spiderTime the value for cms_static_article.spider_time
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setSpiderTime(Date spiderTime) {
        this.spiderTime = spiderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.is_enabled
     *
     * @return the value of cms_static_article.is_enabled
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public Boolean getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.is_enabled
     *
     * @param isEnabled the value for cms_static_article.is_enabled
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.is_delete
     *
     * @return the value of cms_static_article.is_delete
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.is_delete
     *
     * @param isDelete the value for cms_static_article.is_delete
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.create_time
     *
     * @return the value of cms_static_article.create_time
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.create_time
     *
     * @param createTime the value for cms_static_article.create_time
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.create_user
     *
     * @return the value of cms_static_article.create_user
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.create_user
     *
     * @param createUser the value for cms_static_article.create_user
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.update_time
     *
     * @return the value of cms_static_article.update_time
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.update_time
     *
     * @param updateTime the value for cms_static_article.update_time
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.update_user
     *
     * @return the value of cms_static_article.update_user
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.update_user
     *
     * @param updateUser the value for cms_static_article.update_user
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_static_article.article_content
     *
     * @return the value of cms_static_article.article_content
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_static_article.article_content
     *
     * @param articleContent the value for cms_static_article.article_content
     *
     * @mbg.generated 2020-09-29 14:55:10
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent;
    }
}